# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: "3.0.1"
info:
  title: "csvupload"
  version: 0.0.1

servers:
    - url: http://localhost:8080

paths:
    '/api/developers/upload':
        post:
            operationId: uploadDevelopersCsvFile
            tags:
                - 'upload-csv : Developers'
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                fileName:
                                    type: string
                                    format: binary
            responses:
                '200':
                    description: upload successful
                    content:
                        application/text:
                            schema:
                                type: string
