version: '2'
services:
    csvupload-app:
        image: csvupload
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://csvupload-mysql:3306/csvupload?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    csvupload-mysql:
        extends:
            file: mysql.yml
            service: csvupload-mysql
